### ISSUE TITLE
Hidden setting to disable markdown parsing for RSS automations

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#1830]
Related: https://secure.helpscout.net/conversation/2335534049/1299

**Comment by jmduke** [comment]
I no longer think this is a good idea.

**Comment by sobjornstad** [comment]
Would you mind explaining why in a little more detail? This has prevented me from using Buttondown at all, and frankly I don't understand why Markdown is even supported here at all – I've never heard of an RSS feed composed of Markdown.

**Comment by jmduke** [comment]
@sobjornstad I have been sufficiently chastised by my betters (read: I thought this issue was something other than what it was.)

**Comment by jmduke** [comment]
As recompense, I'll get it shipped this week :)

**Comment by sobjornstad** [comment]
Haha, sounds good, thanks!

**Comment by jmduke** [comment]
Note that I think should be a distinction without a difference: we're actually _not_ going to turn off markdown parsing, as a hidden setting or otherwise. Instead, what we're going to do is normalize + prettify the HTML we get from a feed, so that our Markdown parser doesn't think that it's 'markdown'-shaped.

You asked:

> I've never heard of an RSS feed composed of Markdown.

And this is fair, and the explanation belies why we're not turning off Markdown — because the "turn the HTML into Markdown" bit actually isn't even happening at the RSS level. From an architectural perspective, we're basically taking the contents of the RSS feed and plopping it into a new `Email` object (the same kind of email that you'd start writing from scratch), which  _can_ be Markdown!

**Comment by benborgers** [comment]
@jmduke The _only_ issue I have really seen so far is indented `<p>paragraphs</p>` becoming code blocks, so that feels like a reasonable solution!
