### ISSUE TITLE
Discord integration page is broken

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2066]
https://buttondown.email/features/integrations/discord

**Comment by smonette** [comment]
Hey there @jmduke. Looking at the Integrations page, I see that we're linking off to Discord page in Docs (instead of this broken page)

Here's the link:  https://buttondown.email/features/integrations

To resolve this issue, would you prefer we:
1. _fix_ this page in Marketing, then relink it on Integrations
2. Delete this page, check for any existing links to it, and maybe get a redirect in place that points to the Docs article

**Comment by jmduke** [comment]
Let's go with the latter!
