### ISSUE TITLE
Rich → Markdown conversion cannot round trip simple ordered lists

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2342]
```
1. foo
2. bar
```

**Comment by tk04** [comment]
@jmduke just to make sure, this is the bug you're referring to:
From Rich text mode:
![Image](https://github.com/buttondown/roadmap/assets/77863569/2b593112-df02-45ec-ab58-f4c9f5c1c3ff)

To Markdown mode:

![Image](https://github.com/buttondown/roadmap/assets/77863569/23aa34f1-689c-49af-ad05-a9137a08b521)

---
And this should be the desired output (not sure if the extra empty line between list items is intentional):


![Image](https://github.com/buttondown/roadmap/assets/77863569/7db947dc-0de6-4d9d-9102-0898b816c92a)

**Comment by jmduke** [comment]
@tk04 Yup, exactly. (And ideally without that newline!)
