### ISSUE TITLE
Fix malformed Comment JSON

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2503]
https://buttondown.email/EveryEpisodeEver/archive/may-8-1976-the-host-is-madeline-kahn-with-musical/comment/be326218-dcb0-43a3-88c2-b01459da7493

**Comment by catdevnull** [comment]
404 or don't have permission

My guess is that it's because we're generating JSON by templating strings which is.. not ideal. I don't know what the "django way" for generating JSON inside templates is

<img width="865" alt="Screenshot 2024-08-20 at 4 07 09 PM" src="https://github.com/user-attachments/assets/c0b6fafe-a15e-4a48-9281-96adede9c1e6">

**Comment by jmduke** [comment]
I'm guessing this was duplicative of the other thing you fixed anyway. but I do agree that we have a path forward so closing this out.
