### ISSUE TITLE
More granular permission for "can draft email but not send it"

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#2520]
https://secure.helpscout.net/conversation/2529541196/3447

**Comment by jmduke** [comment]
@catdevnull Another fairly small one for you to knock out. I thought about this a little bit and here's an 80%-conviction take: rather than complicate the `none | read | write` permission type and have it be, like `none | read | write | send`, let's just create a net-new permission that is `sending`, as distinct from `emails`. `read` on that permission doesn't actually mean anything, but it lets us keep the actual permission type pure

**Comment by catdevnull** [comment]
two questions:

1. to send an email, a user just has to send the email to status=about_to_send, right? i feel like this should be at least a little better documented in the API docs :stuck_out_tongue:
    1. this also means to conditionally reject a PATCH to an email if it tries to change the status to that but it has no permission to send, right?
1. should we allow users without the sending permission to send draft emails? as far as I can tell, the current implementation allows the user to specify as many subscribers as they want (although they have to know the ID for them) which would technically allow sending a "draft" to all subscribers :)

**Comment by jmduke** [comment]
1. Yes and yes respectively
2. Yes, IMHO. Your understanding is correct from an API design perspective but we do actually have a bevy of controls to make sure folks don't abuse drafts (check out `send_draft.py`)
