### ISSUE TITLE
Fix a myriad of SFI bugs

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3185]
- [x] Default Autonomy-borne automations to `active`
- [x] Fix bug where it's not working for checkboxes
- [ ] ~Move automation creation to backend to prevent O(n) issues~ (This will be covered by #2966)
- [ ] Add support for editing post-creation
- [ ] Migrate to use the same modal flow that `unsubscribereasons` now does in the UI
- [ ] ~Don't allow autonomy if folks don't have `Automations` (and same with `Tags`)~ (This will be covered by #2966)
- [ ] Make sure fields in the actual form are the same order as they are in the author-facing app

**Comment by benborgers** [comment]
@jmduke I think I can still repro this? (I _think_ the backend isn't doing anything with `status`?)

**Comment by jmduke** [comment]
oh no!

**Comment by jmduke** [comment]
@mary-ext When you have some free time / are blocked on Filter groups stuff: if you can give the Subscribe Form Inputs table/flow the same treatment you did for Unsubscription Reasons, that'd be great. (This one's a little trickier because the form itself is a little more complex, but I trust your judgment)

**Comment by rkingett** [comment]
I'm worried I am missing something because this is still broken for checkboxes and creating tags in the hosted forms, but the above says it has been resolved? The checkbox above.

**Comment by rkingett** [comment]
On buttondown it is weirdwriter. I assumed I didn't need to create an automation since automatically tag was on, when adding stuff to the hosted subscribe checkbox field, but let me know if I need to make an automation as well. If so, I can update the docs to reflect this on the user side.

**Comment by rkingett** [comment]
My buttondown username is weirdwriter, but the checkboxes, above, do not appear to be adding tags automatically. For example,

## Steps.

1. Within the hosted subscribe form subscribers interface in settings, I click the button to add a field to the hosted form.
2. For the type, I select, Checkbox.
3. In, key, I enter one word for the key.
4. The label I make as long or short as I need to.
5. I turn on the switch, automatically tag.
6. I hit save.
7. Go into automation settings, and make sure the created automation are enabled.
8. Correct the automations that say, update metadata, to, when a subscriber confirms their subscription, with the filters, when, key equals key, for example, when key, free, equals, key, free, add tags.
note by this point, the result action, add tags, does not always appear in the resulting actions dropdown menu.

9. Click save to save the automations.
10. subscribe to my own mailing list making sure to check my boxes I set up previously. Confirm subscription.
11. View my newly subscribed email to discover there is no tags applied.
## Questions.

1. Do I need to set automations to, when a subscriber updates their metada, instead of when a subscriber confirms their subscription?
2. Is there a way to bundle these filtered automations into one automation with many or filters yet. For example, one automation that has a filter of a key matching OR another key matching another key?
