### ISSUE TITLE
Paginate `/v1/emails/pk/history` 

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3202]

**Comment by catdevnull** [comment]
What's the reason for this? Are the responses being too big? I see it's not as simple as using `generics.list()` because we're using [django-simple-history](https://pypi.org/project/django-simple-history/) and deduping on top of that (https://github.com/buttondown/monorepo/blob/c2b1010303770870a9b782952cdf5dde03a25048/app/emails/models/email/actions/generate_history.py#L13)

**Comment by jmduke** [comment]
@catdevnull Yup, exactly. Some authors have literally _thousands_ of history entries and it's timing out the API request within the UI. 

You're right that it won't be just throwing this in a `generics.list`; I think we'll want to pass a `max` to `generate_history.call`, and cut off the total amount that way. (Realistically, we can be a little lazy here — the main thing is making sure that folks within the UI can page through the first couple hundred entries.)

For a way of building a page without using `generics.list`, check out `list_external_events`.

**Comment by catdevnull** [comment]
Another question: is there an issue in how long it takes the server to execute `email.history.all().reverse()` or is it just that the response is too big and it times out because of the size? I tried figuring this out by looking at Sentry data but it seems there's only one request registered https://buttondown-email.sentry.io/performance/?isDefaultQuery=false&metricSearchSetting=transactionsOnly&project=213773&query=transaction%3A%22%2Fv1%2Femails%2F%7Bid%7D%2Fhistory%22&statsPeriod=14d

I'm asking this because it influences how we go about implementing this (either just limiting the response, or actually querying less from `simple-history` in the first place.) Or if it's not a real issue, we can just limit it to an arbitrary amount (100-500? I don't have data here to decide what's appropiate)

**Comment by catdevnull** [comment]
Okay, it seems that `email.history.all().reverse()` is very fast with 1100 entires locally, so I'm guessing that's not a problem.

However, I've noticed another issue, because the history is currently sent from oldest to latest in the API, but is shown from latest to oldest. If I limit it to 100 entries in the server, it only shows the oldest 100 entries, not the newest 100 entries. Should I change the behavior of the endpoint (which is somewhat of a "breaking" change), or maybe gate it behind a query param (order by latest/oldest)?

**Comment by jmduke** [comment]
Great question and your answer is right on — it's not the DB query that's problematic, just the serialization + deserialization. (One pernicious piece of timeouts, sadly, is that they often don't show up in Sentry because Heroku short-circuits the timeout. Using Kolo (https://kolo.app/) is helpful for this, though.)

I'll run a quick query to confirm, but while flipping the order _is_ a breaking change and if this was a more common method we'd want to think about how to roll this out (eg. just introducing an `ordering` param and starting to use that) I doubt anyone's using this particular endpoint, so feel free to break.
