### ISSUE TITLE
Auto-save scheduling, audience filtering and web archive settings for draft emails

### ISSUE THREAD

**Issue by mary-ext** [buttondown/roadmap#3223]
This got lost after the sending flow revamp (https://github.com/buttondown/roadmap/issues/263) because I wasn't sure how I'd reconcile having auto-save for drafts and manual for sent emails.

It's worth noting that the "Send this email" drawer that is seen on drafts, and the "Email details" drawer that is seen on sent emails, is the _exact same drawer_, there are only a few alterations in how they appear.

Sent emails shouldn't auto-save for these reasons:
- Changing URL slugs and/or audience filters is destructive, having it save in the middle of thought could lead to recipients reading the archives suddenly losing access
- Potential exposure by accident when writing descriptions for the web archive

I *think* I have figured it out, so let's see if we can bring it back.

**Comment by jmduke** [comment]
Relatedly, I had to roll-forward https://github.com/buttondown/monorepo/commit/b49f4c2c1ca6b5973dfc2bb48b291335089101e2 which tweaked some of this logic. Notably, the shift to pull everything in `app/assets/screens/EmailDetail/EmailFinalizationDrawer/Component.vue` was because the API was for some reason complaining about the `subject` not being present... I can dive deeper there.

**Comment by jmduke** [comment]
Oh, and 

> As above, recipients reading the archives could suddenly lose access to what they're reading

This isn't literally true (we keep track of previous slugs in `historical_slugs` to prevent linkrot) but I still agree with your point

**Comment by mary-ext** [comment]
Reopening this since we had to revert it for a bit
