### ISSUE TITLE
Unhandled exception on changing editor mode due to email being undefined

### ISSUE THREAD

**Issue by mary-ext** [buttondown/roadmap#3227]

**Comment by jmduke** [comment]
@mary-ext Re-opening this; had to revert https://github.com/buttondown/monorepo/pull/1573 + https://github.com/buttondown/monorepo/pull/1621. It's not obvious _what_ the root cause — I think it might be the nested watchers? — but there are some lifecycle issues. Steps to repro:

1. Open `/emails/:id`
2. Navigate to some other path
3. Navigate back to `/emails/:id`
4. 80% of the time it will break, and then you can no longer navigate at all until refreshing

**Comment by mary-ext** [comment]
Noticed this as well when jumping between emails, need to take a look tomorrow morning
