### ISSUE TITLE
Allow webhooks to support multiple event types, not just a single one

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3528]

**Comment by catdevnull** [comment]
what's protocol here? I see you've added the field to the model [in this commit](https://github.com/buttondown/monorepo/commit/04b6b22c327bed88e976dcac5479ad3c4eccba58) but didn't migrate the original event_type over.

should I add a migration that does migrate the field over into an array with it? or should it start using event_types and just detect if event_types is not null or use event_type otherwise? it seems like the former would be the right choice, but in that case I'm not sure why you did the model change like that in the first place instead of doing it all in one go

**Comment by jmduke** [comment]
ah that was literally because I was gonna start this and then forgot I assigned it to you 😅 

between the two, the former is the correct move but in this specific case you can ignore it entirely, I can just do a quick one-off in the shell to migrate the existing ones over to the new array field

**Comment by catdevnull** [comment]
>between the two, the former is the correct move but in this specific case you can ignore it entirely, I can just do a quick one-off in the shell to migrate the existing ones over to the new array field

hmm, but do I drop event_type in the PR then? or should it be done after you do the manual migration in prod?

**Comment by jmduke** [comment]
The latter! We'll do it once all of the production traffic is safely reading/writing to the new field.
