### ISSUE TITLE
Fix `sender_score_checker`

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#3533]
We're hitting the rate limits and need to register: https://knowledge.validity.com/s/articles/Accessing-Validity-reputation-data-through-DNS?language=en_US

Let's pair on this for ~15 minutes, as really this is my way of Trojan Horsing you into getting an admin account + access to some light prod data :)

**Comment by catdevnull** [comment]
well, heroku just says "go whitelist all ec2 ips" https://help.heroku.com/JS13Y78I/i-need-to-add-heroku-dynos-to-our-allowlist-what-are-ip-address-ranges-in-use-at-heroku

I'll try that and see what Validity says

**Comment by catdevnull** [comment]
eh, the checker still fails, which makes sense because the query should be going through whatever heroku's default DNS server/resolver is (whatever that is)

I'm not sure what's the "heroku" way to solve this; we can probably self-host an unbound server somewhere, and use something like [`dnspython`](https://dnspython.readthedocs.io/en/stable/query.html#udp) to query it directly instead.

i suppose we can have a heroku dyno running a dns resolver? or somewhere else?

**Comment by catdevnull** [comment]
uh, we seem to be using score.senderscore.com instead of Validity? I just noticed this :')

https://github.com/buttondown/monorepo/blob/698dc2ceba86bca0be737bde991c9009145dd66e/app/emails/deliverability.py#L3

**Comment by catdevnull** [comment]
we probably need to have our own unbound server for these queries, and they should come from the same IP. also, the checker has to be able to access this server somehow.

I'm not sure what's the best approach for this. we could put it in a hetzner VM but then we need to figure out how to make heroku connect to it. 

maybe we can use tailscale, and heroku can get on tailscale with userspace networking: https://tailscale.com/kb/1112/userspace-networking

**Comment by jmduke** [comment]
1. Senderscore is owned by Validity :)
2. Check out the SaaS I dropped in https://github.com/buttondown/roadmap/issues/3551. Should be an easy fix if I understand correctly

**Comment by catdevnull** [comment]
as far as I can tell dnspython by itself doesn't support doing the recursive query by itself, at least not without some helper code which makes me 🤔 

if we had code that did the recursive query itself, we could use QuotaGuard/Fixie:

```
heroku dyno w/ python app -> quotaguard/fixie -> nameservers
```

otherwise, we would need a "static" server with unbound as I mentioned

```
heroku app w/ python app --(vpn? tailscale?)--> unbound running on a server with static IP -> nameservers
```

**Comment by jmduke** [comment]
Ahh, I see — if I'm understanding correctly, this is easy for the RSS use case because we're just using `requests` (and proxying is simple) but since we're hitting `socket` for the sender score case, it's trickier. Is that right?

**Comment by catdevnull** [comment]
not quite. the actual problem is that we need to do the recursive query ourselves as specified by Validity, instead on relying on a recursive DNS server (such as Google's 8.8.8.8, for example). otherwise, Validity only sees a query coming from our DNS server's IP.
